spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: cart
        uri: http://localhost:8081
        predicates:
        - Path=/cart/**
        - Method=GET,POST,PUT
        filters:
        - RewritePath=/cart/(?<segment>.*), /${segment}
      - id: products
        uri: http://localhost:8083
        predicates:
          - Path=/products/**
          - Method=GET
        filters:
          - RewritePath=/products/(?<segment>.*), /${segment}
      - id: checkout
        uri: http://localhost:8082
        predicates:
          - Path=/checkout/**
        filters:
          - RewritePath=/checkout/(?<segment>.*), /${segment}